{
 "title": "Gin Application Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "PV Rate",
   "type": "gauge",
   "description": "Application request rate every 5 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "rate(request_total[5m])" }
   ]
  },
  {
   "title": "PV",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "request_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Traffic In-Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "rate(request_size_bytes[5m])", "legendFormat": "{{instance}}-in" },
    { "expr": "rate(response_size_bytes[5m])", "legendFormat": "{{instance}}-out" }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum (rate(request_duration_seconds_bucket[5m])) by (le, instance))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum (rate(request_duration_seconds_bucket[5m])) by (le, instance))",
     "legendFormat": "p99"
    },
    {
     "expr": "sum (request_duration_seconds_sum) / sum(request_duration_seconds_count)",
     "legendFormat": "avg"
    }
   ]
  }
 ]
}